# @package _global_
to_tensor:
  _target_: emg2qwerty.transforms.ToTensor
  fields: [emg_left, emg_right]

band_rotation:
  _target_: emg2qwerty.transforms.ForEach  # i.i.d rotation offset for each band
  transform:
    _target_: emg2qwerty.transforms.RandomBandRotation
    offsets: [-1, 0, 1]

temporal_jitter:
  _target_: emg2qwerty.transforms.TemporalAlignmentJitter
  max_offset: 120  # Max 60ms jitter for 2kHz EMG

logspec:
  _target_: emg2qwerty.transforms.LogSpectrogram
  n_fft: 64
  hop_length: 16  # Downsamples from 2kHz to 125Hz

specaug:
  _target_: emg2qwerty.transforms.SpecAugment
  n_time_masks: 2 #Changed from 3 to 2
  time_mask_param: 25  # Max 200ms per time mask for 125Hz spectrogram
  n_freq_masks: 1 #Changed from 2 to 1
  freq_mask_param: 4

logspecarbbase:
  _target_: emg2qwerty.transforms.LogSpectrogramArbBase
  n_fft: 64
  hop_length: 16  # Downsamples from 2kHz to 125Hz
  log_base: 4

time_warp:
  _target_: emg2qwerty.transforms.TimeWarp
  max_time_warp: 0.2

add_gaussian_noise:
  _target_: emg2qwerty.transforms.AddGaussianNoise
  mean: 0.0
  std: 0.001

amplitude_random_scaling:
  _target_: emg2qwerty.transforms.AmplitudeRandomScaling
  scale_range: [0.8, 1.2]

channel_dropout:
  _target_: emg2qwerty.transforms.ChannelDropout
  dropout_prob: 1.0

amp_scale:
  _target_: emg2qwerty.transforms.AmplitudeScaling
  fields: [emg_left, emg_right]
  scale_factor: 0.3

band_prefilter:
  _target_: emg2qwerty.transforms.BandpassPreFilter
  lowcut: 10.0
  highcut: 999.0
  fs: 2000.0
  order: 4

transforms:
  train:
    #- ${band_prefilter} #Yep
    #- ${amp_scale} #Yep
    - ${to_tensor}
    #- ${channel_dropout} #Nope
    - ${band_rotation}
    - ${temporal_jitter} #Nope
    #- ${time_warp} 
    #- ${amplitude_random_scaling} #Yep
    #- ${add_gaussian_noise} #Yep
    - ${logspec}
    - ${specaug}

  val:
    #- ${band_prefilter} #Yep
    #- ${amp_scale} #Yep
    - ${to_tensor}
    - ${logspec}

  test: ${transforms.val}
